apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: say-hello
inputs:
  who-to-greet:
    default: "world"
    required: false
outputs:
  greeting: ${{ steps.greet.outputs.message }}
runs:
  using: composite
  steps:
    - id: greet
      name: Greet
      uses: docker://golang:1.20.3-alpine3.17
      shell: sh
      run: |
        echo "Hello ${{ inputs.who-to-greet }}" > "$CLOUDBEES_OUTPUTS/message"
